# Generated by Django 6.0 on 2026-02-27 15:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('boolean', 'Boolean'), ('number', 'Number'), ('json', 'JSON')], default='text', max_length=20)),
                ('category', models.CharField(choices=[('general', 'General'), ('financial', 'Financial'), ('logistics', 'Logistics'), ('notifications', 'Notifications'), ('system', 'System')], default='general', max_length=20)),
                ('is_public', models.BooleanField(default=True, help_text='Whether this parameter is visible to the frontend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Parameter',
                'verbose_name_plural': 'System Parameters',
                'ordering': ['category', 'name'],
            },
        ),
    ]
