# Generated by Django 6.0 on 2026-03-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierpurchases', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpurchase',
            name='image_url',
        ),
        migrations.AddField(
            model_name='supplierpurchase',
            name='image_urls',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
