# Generated by Django 6.0 on 2025-12-31 06:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country_origin', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received'), ('COMPLETED', 'Completed')], max_length=20)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='currencies.currency')),
            ],
        ),
    ]
