# Generated by Django 6.0 on 2026-02-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_remove_shipment_product_name_shipmentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='actual_arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='estimated_transit_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
