# Generated by Django 6.0 on 2025-12-31 06:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('rate_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates_from', to='currencies.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates_to', to='currencies.currency')),
            ],
            options={
                'ordering': ['-rate_date'],
                'unique_together': {('from_currency', 'to_currency', 'rate_date')},
            },
        ),
    ]
