# Generated by Django 6.0 on 2026-02-26 15:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('exchangerates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyMargin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('margin_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage markup to apply (e.g., 2.00 for 2%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margins_from', to='currencies.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margins_to', to='currencies.currency')),
            ],
            options={
                'unique_together': {('from_currency', 'to_currency')},
            },
        ),
    ]
