# Generated by Django 6.0 on 2025-12-31 06:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('net_received_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transport_loss_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('freezing_loss_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('facility_location', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
