# Generated by Django 6.0 on 2025-12-31 06:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost_category', models.CharField(choices=[('Transport', 'Transport'), ('Freezing', 'Freezing'), ('Cold Storage', 'Cold Storage'), ('Packing Materials', 'Packing Materials'), ('Labor', 'Labor'), ('Commissions', 'Commissions'), ('Export Fees', 'Export Fees'), ('Fuel', 'Fuel'), ('Accommodation', 'Accommodation'), ('Meals', 'Meals'), ('Miscellaneous', 'Miscellaneous')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('other_category', models.CharField(blank=True, help_text='Required if category is Miscellaneous', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exchange_rate_used', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('converted_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_ledgers', to='currencies.currency')),
            ],
        ),
    ]
